[
{"name": "月光宝盒",     "url": "https://agit.ai/guot54/ygbh/raw/branch/master/zB/tvlive.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "肥猫",     "url": "http://我不是.肥猫.love:63/TV/tvzb.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "饭太硬",     "url": "https://ghproxy.com/raw.githubusercontent.com/dxawi/0/main/tvlive.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name":"范明","url":"https://ghproxy.com/raw.githubusercontent.com/fanmingming/live/main/tv/m3u/global.m3u&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "乌云m3u8",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/wuyun999/wuyun/main/zb/aptv.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "多多",     "url": "https://yydsys.top/duo/txt/v.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "经典坐标","url": "https://gitea.com/livetvbox/tvbox/raw/branch/master/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "RUSFILM RULIST2","url": "https://agit.ai/kuku/kot/raw/branch/master/tv/RUSLI2.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "RUSFILM 0001-1000","url": "https://agit.ai/kuku/kot/raw/branch/master/tv/RUSFILM%200001-1000.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "RUSFILM 1001-2000","url": "https://agit.ai/kuku/kot/raw/branch/master/tv/RUSFILM%201001-2000.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "RUSFILM 2001-3000","url": "https://agit.ai/kuku/kot/raw/branch/master/tv/RUSFILM%202001-3000.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "RUSFILM 3001-4000","url": "https://agit.ai/kuku/kot/raw/branch/master/tv/RUSFILM%203001-4000.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "BESTVm3u8",     "url": "https://telegram-feiyangdigital.v1.mk/bestv.m3u&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "肥羊精选",     "url": "https://telegram-feiyangdigital.v1.mk&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "APTVipv6",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "zbefine",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/zbefine/iptv/main/iptv.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "茶客m3u8",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/vamoschuck/TV/main/M3U&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "虎牙m3u8",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/ya.m3u&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "斗鱼m3u8",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/yu.m3u&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "霜辉月明",     "url": "http://tv.jthn.cn/lives/live_plus.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "甜蜜",     "url": "http://zdir.kebedd69.repl.co/public/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "星辰",     "url": "http://tvmvip.com/xclive.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "俊于",     "url": "http://home.jundie.top:81/Cat/tv/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "菜妮丝",     "url": "http://xn--ihqu10cn4c.xn--z7x900a.love:63/TV/tvzb.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "吾爱",     "url": "http://52bsj.vip:81/api/v3/file/get/763/live.txt?sign=87BTGT1_6AOry7FPwy_uuxFTv2Wcb9aDMj46rDdRTD8%3D%3A0&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "饭太硬",     "url": "http://ftyyy.tk/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "老刘备",     "url": "http://9xi4o.tk/sub/mytv.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "南风线路",     "url": "https://agit.ai/Yoursmile7/TVBox/raw/branch/master/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "潇洒线路",     "url": "https://download.kstore.space/download/2863/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "宝盒科技",     "url": "http://52bsj.vip:81/api/v3/file/get/79119/ZB.txt?sign=iChDXDC7WJRTp7yWAyVdbY3si5sJ5eFwEgaR35YQGSo%3D%3A0&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "瞄影视线路",     "url": "http://miaotvs.cn/meowzb&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "佰欣园线路",     "url": "https://ghproxy.com/https://raw.githubusercontent.com/chengxueli818913/maoTV/main/live%20(1).txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "一影视线路",     "url": "http://home.jundie.top:81/Cat/tv/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "一木线路",     "url": "http://home.jundie.top:81/ray/tvlive.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "二哈线路",     "url": "http://ftp6284928.host108.abeiyun.cn/live/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "zzz1线路",     "url": "http://freed.yuanhsing.cf/tv/live.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"},
{"name": "影视",     "url": "https://agit.ai/gk0747/1/raw/branch/master/zb.txt&&&https://agit.ai/kuku/kot/raw/branch/master/js/icon_img_placeholder6.png"}
]